apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
      - name: dummy-app
        image: dummy-app:latest # Will be replaced by CI-built image
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-app-service
spec:
  selector:
    app: dummy-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP